all:
	gcc -Wall -g -o pb02_ptd pb02_ptd.c -lpthread
	gcc -Wall -g -o pb02_omp pb02_omp.c -fopenmp
	g++ -Wall -g -o pb01_omp pb01_omp.cpp -fopenmp
	g++ -Wall -g -o pb01_ptd pb01_ptd.cpp -lpthread
	gcc -Wall -g -o pb03 pb03.c

